# Generated by Django 4.0.3 on 2022-07-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=500)),
                ('stock', models.IntegerField()),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('precioVentaProm', models.IntegerField()),
                ('idProveedor', models.IntegerField()),
                ('fecRecepcion', models.DateField()),
                ('fecProxCompra', models.DateField()),
            ],
        ),
    ]
