# Generated by Django 4.0.3 on 2022-07-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bding', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoVenta',
        ),
    ]
